name: Build & Push Docker CI Image

# Careful, code duplication with test-ci-image-build.yml
# Inspired by: https://github.com/docker/build-push-action/issues/50

on:
  pull_request:
    types: [closed]

jobs:
  tag:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Print variables
        run: |
                echo "GH Ref: ${{github.ref}}"
                echo "GH Ref 2: ${GITHUB_REF##*/}"
